export const CATEGORIES_RECEIVES_LIST = "CATEGORIES_RECEIVES_LIST";
export const CATEGORIES_HIDE_SPINNER = "CATEGORIES_HIDE_SPINNER";
export const CATEGORIES_SHOW_SPINNER = "CATEGORIES_SHOW_SPINNER";
